name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  env:
    GITHUB_TOKEN: ${{ secrets.TEST }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Release DLL
      uses: softprops/action-gh-release@v1
      with:
      tag_name: SharpBoot-Release
      name: SharpBoot Release
      files: | 
        Wait.img
