name: Build SharpBoot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore && echo "::set-output name=today::$(date +"%d-%m-%y")"


    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
            /home/runner/work/SharpBoot/SharpBoot/SharpBoot/bin/Debug/net472/SharpBoot.dll
        name: SharpBoot Release
        tag_name: ${{ steps.Build.outputs.today }}
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
